---
title: Jack of All Trades
timezone: Asia/Jakarta
collections:
  home:
    title: Home
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Master of All
disqus_shortname: danieljuvito
reading_time: true
words_per_minute: 200
url: 
owner:
  name: Daniel Juvito
  avatar: vito.jpg
  bio: Human Wannabe.
  email: danieljuvito@gmail.com
  twitter: danieljuvito
  facebook: danieljuvito
  github: danieljuvito
  stackexchange: 
  linkedin: 
  instagram: danieljuvito
  flickr: 
  tumblr: 
  google_plus: 
background: 
google_analytics: 
google_verify: 
bing_verify: 
future: false
highlighter: rouge
markdown: kramdown
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
include:
- ".htaccess"
exclude:
- "*.less"
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- lib
- log
- node_modules
- package.json
- spec
- tmp
- _excludes
gist:
  noscript: false
