---
title: Daniel Juvito
timezone: Asia/Jakarta
collections:
  home:
    title: Home
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
owner:
  name: Daniel Allan Juvito
  email: danieljuvito@gmail.com
  twitter: danieljuvito
  github: danieljuvito
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-coffeescript
